---
- name: Set up EC2 instance for Yii2 application
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install docker-compose
      apt:
        name: docker-compose
        state: present

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Initialize Docker Swarm
      command: docker swarm init
      ignore_errors: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Copy Nginx host configuration
      copy:
        src: infra/nginx-host.conf
        dest: /etc/nginx/sites-available/yii.zubera.one
      notify: Restart Nginx

    - name: Copy docker-compose.yml
      copy:
        src: /app/docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Pull Docker image
      community.docker.docker_image:
        name: jeevayovan/yii2-app:latest
        source: pull
      become: no
      delegate_to: localhost

    - name: Deploy Docker stack
      community.docker.docker_stack:
        name: myapp
        compose: /home/ubuntu/docker-compose.yml
        state: present
      become: no

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted