name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Verify Docker is installed on runner
        run: |
          docker --version

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build and push Docker image
      #   run: |
      #     docker build -t jeevayovan/yii2-app:latest -f app/Dockerfile app/
      #     docker push jeevayovan/yii2-app:latest

      # - name: Install Ansible on runner
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y ansible python3-pip

      - name: Install Python dependencies for Ansible
        run: |
          python3 -m pip install --user requests jsondiff PyYAML docker

      - name: Install community.docker collection for Ansible
        run: ansible-galaxy collection install community.docker:==3.5.0

      - name: Run Ansible playbook to deploy on EC2
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > websites-key-sig.pem
          chmod 400 websites-key-sig.pem
          ansible-playbook -i ${{ secrets.EC2_HOST }}, infra/setup.yml --user ubuntu --key-file websites-key-sig.pem
